"""Add expenses table

Revision ID: 70348a4131e3
Revises: 86e74324a732
Create Date: 2026-04-04 20:23:38.955841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70348a4131e3'
down_revision = '86e74324a732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('paid_by', sa.String(length=30), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
